### ISSUE TITLE
Problems with grammer highlight

### ISSUE THREAD

**Issue by RoadToDream** [SE2Dev/vscode-yacc#1]
Seems not compatible with the latest version of vs code, will you please fix it?
![image](https://cloud.githubusercontent.com/assets/8088354/24838344/e1ba54e0-1d78-11e7-8077-08cb6c5f2d97.png)

**Comment by SE2Dev** [comment]
I suspect this is related to the grammar injections as I had numerous issues with them when initially writing the grammar file.
I'm going to look into dynamically setting the syntax for parts of the code via plugin.

**Comment by SE2Dev** [comment]
I have resolved the C++ syntax highlighting issue, and published an update (v1.1.0).

**Comment by RoadToDream** [comment]
Thanks very much! It's a great help.
